// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QNZ.Data
{
    [Table("AgentSet")]
    public partial class AgentSet
    {
        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        /// <summary>
        /// 微信号
        /// </summary>
        public string WechatId { get; set; }
        [Required]
        [StringLength(11)]
        /// <summary>
        /// 手机
        /// </summary>
        public string Mobile { get; set; }
        [Required]
        [StringLength(50)]
        /// <summary>
        /// 名称
        /// </summary>
        public string Name { get; set; }
        [Required]
        [StringLength(50)]
        /// <summary>
        /// 省
        /// </summary>
        public string Province { get; set; }
        [StringLength(50)]
        /// <summary>
        /// 市
        /// </summary>
        public string City { get; set; }
        [StringLength(50)]
        /// <summary>
        /// 区/县
        /// </summary>
        public string District { get; set; }
        [Required]
        [StringLength(50)]
        /// <summary>
        /// 负责人
        /// </summary>
        public string Principal { get; set; }
        [Required]
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [StringLength(50)]
        public string UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
    }
}