// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QNZ.Data
{
    public partial class Branch
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(150)]
        public string Name { get; set; }
        [StringLength(500)]
        public string Summary { get; set; }
        public string Body { get; set; }
        [StringLength(150)]
        public string Address { get; set; }
        [StringLength(150)]
        public string Homepage { get; set; }
        [StringLength(150)]
        public string ImageUrl { get; set; }
        [Required]
        [StringLength(150)]
        public string Contact { get; set; }
        [Required]
        [StringLength(300)]
        public string Business { get; set; }
        public int ViewCount { get; set; }
        public int Importance { get; set; }
        [Required]
        public bool? Active { get; set; }
        [Required]
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [StringLength(50)]
        public string UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
    }
}