// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QNZ.Data
{
    [Table("CartItem")]
    public partial class CartItem
    {
        [Key]
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public int CartId { get; set; }
        public int StoreId { get; set; }

        [ForeignKey(nameof(CartId))]
        [InverseProperty("CartItems")]
        public virtual Cart Cart { get; set; }
        [ForeignKey(nameof(StoreId))]
        [InverseProperty("CartItems")]
        public virtual Store Store { get; set; }
    }
}