// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QNZ.Data
{
    public partial class Document
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(150)]
        public string Title { get; set; }
        [StringLength(300)]
        public string Description { get; set; }
        [StringLength(150)]
        public string FileUrl { get; set; }
        public long FileSize { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Pubdate { get; set; }
        public int DownloadCount { get; set; }
        [Required]
        public bool? Active { get; set; }
        public int CategoryId { get; set; }
        [Required]
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [StringLength(50)]
        public string UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }

        [ForeignKey(nameof(CategoryId))]
        [InverseProperty(nameof(DocCategory.Documents))]
        public virtual DocCategory Category { get; set; }
    }
}