// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QNZ.Data
{
    [Table("FeedbackSet")]
    public partial class FeedbackSet
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string OpenId { get; set; }
        public int FeedbackTypeId { get; set; }
        [Required]
        [StringLength(500)]
        public string Message { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [StringLength(500)]
        public string ImageUrls { get; set; }
        [StringLength(50)]
        public string Mobile { get; set; }

        [ForeignKey(nameof(FeedbackTypeId))]
        [InverseProperty(nameof(FeedbackTypeSet.FeedbackSets))]
        public virtual FeedbackTypeSet FeedbackType { get; set; }
        [ForeignKey(nameof(OpenId))]
        [InverseProperty(nameof(Customer.FeedbackSets))]
        public virtual Customer Open { get; set; }
    }
}