// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QNZ.Data
{
    [Table("FeedbackTypeSet")]
    public partial class FeedbackTypeSet
    {
        public FeedbackTypeSet()
        {
            FeedbackSets = new HashSet<FeedbackSet>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Title { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [Required]
        [StringLength(50)]
        public string CreatedBy { get; set; }

        [InverseProperty(nameof(FeedbackSet.FeedbackType))]
        public virtual ICollection<FeedbackSet> FeedbackSets { get; set; }
    }
}