// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QNZ.Data
{
    public partial class Job
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(150)]
        public string Title { get; set; }
        public string Description { get; set; }
        [StringLength(150)]
        public string Department { get; set; }
        [StringLength(150)]
        public string Address { get; set; }
        public int Number { get; set; }
        public int Importance { get; set; }
        [Required]
        public bool? Active { get; set; }
        public int CategoryId { get; set; }
        [Required]
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [StringLength(50)]
        public string UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
        public int? BranchId { get; set; }
        [StringLength(150)]
        public string HrEmail { get; set; }

        [ForeignKey(nameof(BranchId))]
        [InverseProperty("Jobs")]
        public virtual Branch Branch { get; set; }
        [ForeignKey(nameof(CategoryId))]
        [InverseProperty(nameof(JobCategory.Jobs))]
        public virtual JobCategory Category { get; set; }
    }
}