// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.SqlTypes;

namespace QNZ.Data
{
    [Table("Logs")]
    public partial class Log
    {
        [Key]
        public int Id { get; set; }
        public string Message { get; set; }
        public string MessageTemplate { get; set; }
        [StringLength(128)]
        public string Level { get; set; }
       
        public DateTimeOffset TimeStamp { get; set; }
        public string Exception { get; set; }
        // public SqlXml Properties { get; set; }
        public string LogEvent { get; set; }
        [StringLength(200)]
        public string UserName { get; set; }
        [StringLength(50)]
        public string IP { get; set; }

    }
}