// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QNZ.Data
{
    public partial class NavigationCategory
    {
        public NavigationCategory()
        {
            Navigations = new HashSet<Navigation>();
        }

        [Key]
        public int Id { get; set; }
        public int Importance { get; set; }
        public bool IsSys { get; set; }
        [Required]
        [StringLength(50)]
        public string Title { get; set; }
        public bool Active { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [StringLength(50)]
        public string UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }

        [InverseProperty(nameof(Navigation.Category))]
        public virtual ICollection<Navigation> Navigations { get; set; }
    }
}