// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QNZ.Data
{
    public partial class Navigation
    {
        public Navigation()
        {
            InverseParent = new HashSet<Navigation>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Title { get; set; }
        public bool Active { get; set; }
        [StringLength(150)]
        public string Url { get; set; }
        public int CategoryId { get; set; }
        [StringLength(150)]
        public string Iconfont { get; set; }
        public int Importance { get; set; }
        public bool IsExpand { get; set; }
        public int? LayoutLevel { get; set; }
        public short MenuType { get; set; }
        public int? ParentId { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [StringLength(50)]
        public string UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }

        [ForeignKey(nameof(CategoryId))]
        [InverseProperty(nameof(NavigationCategory.Navigations))]
        public virtual NavigationCategory Category { get; set; }
        [ForeignKey(nameof(ParentId))]
        [InverseProperty(nameof(Navigation.InverseParent))]
        public virtual Navigation Parent { get; set; }
        [InverseProperty(nameof(Navigation.Parent))]
        public virtual ICollection<Navigation> InverseParent { get; set; }
    }
}