// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QNZ.Data
{
    public partial class PageMeta
    {
        [StringLength(100)]
        public string Title { get; set; }
        public string Description { get; set; }
        public string Keywords { get; set; }
        [Key]
        public short ModuleType { get; set; }
        [Key]
        [StringLength(100)]
        public string ObjectId { get; set; }
    }
}