// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QNZ.Data
{
    public partial class PostTagesLinkPost
    {
        [Key]
        public int PostId { get; set; }
        [Key]
        public int TagId { get; set; }

        [ForeignKey(nameof(PostId))]
        [InverseProperty("PostTagesLinkPosts")]
        public virtual Post Post { get; set; }
        [ForeignKey(nameof(TagId))]
        [InverseProperty(nameof(PostTag.PostTagesLinkPosts))]
        public virtual PostTag Tag { get; set; }
    }
}