// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QNZ.Data
{
    public partial class PostTag
    {
        public PostTag()
        {
            PostTagesLinkPosts = new HashSet<PostTagesLinkPost>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string TagName { get; set; }

        [InverseProperty(nameof(PostTagesLinkPost.Tag))]
        public virtual ICollection<PostTagesLinkPost> PostTagesLinkPosts { get; set; }
    }
}