// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QNZ.Data
{
    [Table("RecipesItem")]
    public partial class RecipesItem
    {
        [Key]
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int RecipesId { get; set; }
        public int Quantity { get; set; }

        [ForeignKey(nameof(ProductId))]
        [InverseProperty("RecipesItems")]
        public virtual Product Product { get; set; }
        [ForeignKey(nameof(RecipesId))]
        [InverseProperty(nameof(Recipe.RecipesItems))]
        public virtual Recipe Recipes { get; set; }
    }
}