// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QNZ.Data
{
    public partial class Recipe
    {
        public Recipe()
        {
            CustomerRecipes = new HashSet<CustomerRecipe>();
            RecipesItems = new HashSet<RecipesItem>();
        }

        [Key]
        public int Id { get; set; }
        public Guid UserId { get; set; }
        [Required]
        [StringLength(100)]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [StringLength(50)]
        public string CustomerMobile { get; set; }

        [InverseProperty(nameof(CustomerRecipe.Recipes))]
        public virtual ICollection<CustomerRecipe> CustomerRecipes { get; set; }
        [InverseProperty(nameof(RecipesItem.Recipes))]
        public virtual ICollection<RecipesItem> RecipesItems { get; set; }
    }
}