// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QNZ.Data
{
    [Table("RoleMenu")]
    public partial class RoleMenu
    {
        [Key]
        public int RoleId { get; set; }
        [Key]
        public int MenuId { get; set; }

        [ForeignKey(nameof(MenuId))]
        [InverseProperty("RoleMenus")]
        public virtual Menu Menu { get; set; }
        [ForeignKey(nameof(RoleId))]
        [InverseProperty("RoleMenus")]
        public virtual Role Role { get; set; }
    }
}