// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QNZ.Data
{
    public partial class Staff
    {
        [Key]
        public int Id { get; set; }
        [StringLength(150)]
        public string Photo { get; set; }
        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        [StringLength(50)]
        public string Gender { get; set; }
        [StringLength(100)]
        public string Referrer { get; set; }
        [StringLength(100)]
        public string MasterTime { get; set; }
        [StringLength(100)]
        public string Post { get; set; }
        public string Description { get; set; }
        [Required]
        public bool? Active { get; set; }
        public int OrganizationId { get; set; }
        public int Importance { get; set; }
        [Required]
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [StringLength(50)]
        public string UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }

        [ForeignKey(nameof(OrganizationId))]
        [InverseProperty("staff")]
        public virtual Organization Organization { get; set; }
    }
}