// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QNZ.Data
{
    [Table("Store")]
    public partial class Store
    {
        public Store()
        {
            CartItems = new HashSet<CartItem>();
            OrderDetails = new HashSet<OrderDetail>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        /// <summary>
        /// 店铺名称
        /// </summary>
        public string Name { get; set; }
        [Required]
        [StringLength(50)]
        /// <summary>
        /// 联系人
        /// </summary>
        public string Contact { get; set; }
        [Required]
        [StringLength(50)]
        /// <summary>
        /// 电话
        /// </summary>
        public string Phone { get; set; }
        [Required]
        [StringLength(250)]
        /// <summary>
        /// 地址
        /// </summary>
        public string Address { get; set; }
        [Required]
        [StringLength(50)]
        /// <summary>
        /// 省
        /// </summary>
        public string Province { get; set; }
        [StringLength(50)]
        /// <summary>
        /// 城市 
        /// </summary>
        public string City { get; set; }
        [StringLength(50)]
        /// <summary>
        /// 区/县
        /// </summary>
        public string District { get; set; }
        [StringLength(150)]
        public string Thumbnail { get; set; }
        [Column(TypeName = "decimal(10, 6)")]
        /// <summary>
        /// 经度
        /// </summary>
        public decimal Longitude { get; set; }
        [Column(TypeName = "decimal(10, 6)")]
        public decimal Latitude { get; set; }
        [Required]
        [StringLength(50)]
        /// <summary>
        /// 创建人
        /// </summary>
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreatedDate { get; set; }
        [StringLength(50)]
        /// <summary>
        /// 最后更新人
        /// </summary>
        public string UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        /// <summary>
        /// 最后更新时间
        /// </summary>
        public DateTime? UpdatedDate { get; set; }
        public string Body { get; set; }

        [InverseProperty(nameof(CartItem.Store))]
        public virtual ICollection<CartItem> CartItems { get; set; }
        [InverseProperty(nameof(OrderDetail.Store))]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}