// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QNZ.Data
{
    public partial class Video
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        /// <summary>
        /// 微信号
        /// </summary>
        public string Title { get; set; }
        [Required]
        [StringLength(150)]
        /// <summary>
        /// 手机
        /// </summary>
        public string Cover { get; set; }
        [StringLength(150)]
        /// <summary>
        /// 名称
        /// </summary>
        public string VideoUrl { get; set; }
        [StringLength(250)]
        /// <summary>
        /// 省
        /// </summary>
        public string Description { get; set; }
        public int Importance { get; set; }
        public bool Active { get; set; }
        public bool Recommend { get; set; }
        [Required]
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [StringLength(50)]
        public string UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedDate { get; set; }
    }
}