//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.Resources.Admin {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EntityNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntityNames() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIG.Resources.Admin.EntityNames", typeof(EntityNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 代理商 的本地化字符串。
        /// </summary>
        public static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相册 的本地化字符串。
        /// </summary>
        public static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公告 的本地化字符串。
        /// </summary>
        public static string Announcement {
            get {
                return ResourceManager.GetString("Announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新闻 的本地化字符串。
        /// </summary>
        public static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文章分类 的本地化字符串。
        /// </summary>
        public static string ArticleCategory {
            get {
                return ResourceManager.GetString("ArticleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轮播图 的本地化字符串。
        /// </summary>
        public static string Carousel {
            get {
                return ResourceManager.GetString("Carousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购物车 的本地化字符串。
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类 的本地化字符串。
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纪事 的本地化字符串。
        /// </summary>
        public static string Chronicle {
            get {
                return ResourceManager.GetString("Chronicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 城市 的本地化字符串。
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户 的本地化字符串。
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区县 的本地化字符串。
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮件 的本地化字符串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱帐号 的本地化字符串。
        /// </summary>
        public static string EmailAccount {
            get {
                return ResourceManager.GetString("EmailAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮件模板 的本地化字符串。
        /// </summary>
        public static string EmailTemplate {
            get {
                return ResourceManager.GetString("EmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仪器设备 的本地化字符串。
        /// </summary>
        public static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反馈意见 的本地化字符串。
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反馈类型 的本地化字符串。
        /// </summary>
        public static string FeedbackType {
            get {
                return ResourceManager.GetString("FeedbackType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集模板 的本地化字符串。
        /// </summary>
        public static string FilterTemplate {
            get {
                return ResourceManager.GetString("FilterTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货品 的本地化字符串。
        /// </summary>
        public static string Goods {
            get {
                return ResourceManager.GetString("Goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货品分类 的本地化字符串。
        /// </summary>
        public static string GoodsCategory {
            get {
                return ResourceManager.GetString("GoodsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货品图片 的本地化字符串。
        /// </summary>
        public static string GoodsPhoto {
            get {
                return ResourceManager.GetString("GoodsPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人才招聘 的本地化字符串。
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接 的本地化字符串。
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接分类 的本地化字符串。
        /// </summary>
        public static string LinkCategory {
            get {
                return ResourceManager.GetString("LinkCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志 的本地化字符串。
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单 的本地化字符串。
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 栏目分类 的本地化字符串。
        /// </summary>
        public static string MenuCategory {
            get {
                return ResourceManager.GetString("MenuCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单 的本地化字符串。
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单明细 的本地化字符串。
        /// </summary>
        public static string OrderDetail {
            get {
                return ResourceManager.GetString("OrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面 的本地化字符串。
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面注释 的本地化字符串。
        /// </summary>
        public static string PageMeta {
            get {
                return ResourceManager.GetString("PageMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限 的本地化字符串。
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 照片 的本地化字符串。
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 广告位 的本地化字符串。
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 博文 的本地化字符串。
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 博文分类 的本地化字符串。
        /// </summary>
        public static string PostCategory {
            get {
                return ResourceManager.GetString("PostCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品 的本地化字符串。
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品分类 的本地化字符串。
        /// </summary>
        public static string ProductCategory {
            get {
                return ResourceManager.GetString("ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品图片 的本地化字符串。
        /// </summary>
        public static string ProductPhoto {
            get {
                return ResourceManager.GetString("ProductPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 省份 的本地化字符串。
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常见问题 的本地化字符串。
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 问题分类 的本地化字符串。
        /// </summary>
        public static string QuestionCategory {
            get {
                return ResourceManager.GetString("QuestionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件信息 的本地化字符串。
        /// </summary>
        public static string RecipientInfo {
            get {
                return ResourceManager.GetString("RecipientInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解决方案 的本地化字符串。
        /// </summary>
        public static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 门店 的本地化字符串。
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 企业故事 的本地化字符串。
        /// </summary>
        public static string Story {
            get {
                return ResourceManager.GetString("Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 团队 的本地化字符串。
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工艺 的本地化字符串。
        /// </summary>
        public static string Technology {
            get {
                return ResourceManager.GetString("Technology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户安全 的本地化字符串。
        /// </summary>
        public static string UserSafety {
            get {
                return ResourceManager.GetString("UserSafety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频 的本地化字符串。
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 案例 的本地化字符串。
        /// </summary>
        public static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 案例分类 的本地化字符串。
        /// </summary>
        public static string WorkCategory {
            get {
                return ResourceManager.GetString("WorkCategory", resourceCulture);
            }
        }
    }
}
