//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QNZ.Resources.Admin {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QNZ.Resources.Admin.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 帐号ID 的本地化字符串。
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激活 的本地化字符串。
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 广告位 的本地化字符串。
        /// </summary>
        public static string AdvertisingSpace {
            get {
                return ResourceManager.GetString("AdvertisingSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年龄 的本地化字符串。
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代理商 的本地化字符串。
        /// </summary>
        public static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代理商名称 的本地化字符串。
        /// </summary>
        public static string AgentName {
            get {
                return ResourceManager.GetString("AgentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相册 的本地化字符串。
        /// </summary>
        public static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 别名 的本地化字符串。
        /// </summary>
        public static string Alias {
            get {
                return ResourceManager.GetString("Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 答案 的本地化字符串。
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平台类型 的本地化字符串。
        /// </summary>
        public static string AppType {
            get {
                return ResourceManager.GetString("AppType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 面积 的本地化字符串。
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文章数量 的本地化字符串。
        /// </summary>
        public static string ArticleCount {
            get {
                return ResourceManager.GetString("ArticleCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作者 的本地化字符串。
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 头像 的本地化字符串。
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 百度统计代号 的本地化字符串。
        /// </summary>
        public static string BaiduSiteID {
            get {
                return ResourceManager.GetString("BaiduSiteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条形码 的本地化字符串。
        /// </summary>
        public static string Barcode {
            get {
                return ResourceManager.GetString("Barcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生日 的本地化字符串。
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 展位 的本地化字符串。
        /// </summary>
        public static string Booth {
            get {
                return ResourceManager.GetString("Booth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缓存时间（分钟） 的本地化字符串。
        /// </summary>
        public static string CacheDuration {
            get {
                return ResourceManager.GetString("CacheDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 店员帐号 的本地化字符串。
        /// </summary>
        public static string Cashier {
            get {
                return ResourceManager.GetString("Cashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类 的本地化字符串。
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类图片高度 的本地化字符串。
        /// </summary>
        public static string CategoryImageHeight {
            get {
                return ResourceManager.GetString("CategoryImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类图片宽度 的本地化字符串。
        /// </summary>
        public static string CategoryImageWidth {
            get {
                return ResourceManager.GetString("CategoryImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 市 的本地化字符串。
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户 的本地化字符串。
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户名称 的本地化字符串。
        /// </summary>
        public static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭原因 的本地化字符串。
        /// </summary>
        public static string CloseInfo {
            get {
                return ResourceManager.GetString("CloseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编码 的本地化字符串。
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司 的本地化字符串。
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司名称 的本地化字符串。
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司名称 的本地化字符串。
        /// </summary>
        public static string CompayName {
            get {
                return ResourceManager.GetString("CompayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码 的本地化字符串。
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系方式 的本地化字符串。
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 坐标 的本地化字符串。
        /// </summary>
        public static string Coordinate {
            get {
                return ResourceManager.GetString("Coordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 封面 的本地化字符串。
        /// </summary>
        public static string Cover {
            get {
                return ResourceManager.GetString("Cover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建者 的本地化字符串。
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言编码 的本地化字符串。
        /// </summary>
        public static string CultureName {
            get {
                return ResourceManager.GetString("CultureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 垫层 的本地化字符串。
        /// </summary>
        public static string CUSHION {
            get {
                return ResourceManager.GetString("CUSHION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户 的本地化字符串。
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户手机号 的本地化字符串。
        /// </summary>
        public static string CustomerMobile {
            get {
                return ResourceManager.GetString("CustomerMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logo（控制面版） 的本地化字符串。
        /// </summary>
        public static string DashboardLogo {
            get {
                return ResourceManager.GetString("DashboardLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期 的本地化字符串。
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束日期 的本地化字符串。
        /// </summary>
        public static string DateEnd {
            get {
                return ResourceManager.GetString("DateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始日期 的本地化字符串。
        /// </summary>
        public static string DateStart {
            get {
                return ResourceManager.GetString("DateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日 的本地化字符串。
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 演示网址 的本地化字符串。
        /// </summary>
        public static string Demourl {
            get {
                return ResourceManager.GetString("Demourl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门 的本地化字符串。
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昵称 的本地化字符串。
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区/县 的本地化字符串。
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档 的本地化字符串。
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子邮箱 的本地化字符串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮件帐号 的本地化字符串。
        /// </summary>
        public static string EmailAccount {
            get {
                return ResourceManager.GetString("EmailAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 招聘接收简历邮箱 的本地化字符串。
        /// </summary>
        public static string EmailHr {
            get {
                return ResourceManager.GetString("EmailHr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启缓存 的本地化字符串。
        /// </summary>
        public static string EnableCaching {
            get {
                return ResourceManager.GetString("EnableCaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英文标题 的本地化字符串。
        /// </summary>
        public static string EnglishTitle {
            get {
                return ResourceManager.GetString("EnglishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仪器数量 的本地化字符串。
        /// </summary>
        public static string EquipmentCount {
            get {
                return ResourceManager.GetString("EquipmentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 面料 的本地化字符串。
        /// </summary>
        public static string FABRIC {
            get {
                return ResourceManager.GetString("FABRIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传真 的本地化字符串。
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反馈类型 的本地化字符串。
        /// </summary>
        public static string FeedbackType {
            get {
                return ResourceManager.GetString("FeedbackType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档 的本地化字符串。
        /// </summary>
        public static string FileUrl {
            get {
                return ResourceManager.GetString("FileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成年份 的本地化字符串。
        /// </summary>
        public static string FinishYear {
            get {
                return ResourceManager.GetString("FinishYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体图标 的本地化字符串。
        /// </summary>
        public static string FontIcon {
            get {
                return ResourceManager.GetString("FontIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式不正确 的本地化字符串。
        /// </summary>
        public static string FormatInvalid {
            get {
                return ResourceManager.GetString("FormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大图 的本地化字符串。
        /// </summary>
        public static string FullImage {
            get {
                return ResourceManager.GetString("FullImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全称 的本地化字符串。
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别 的本地化字符串。
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货品名称 的本地化字符串。
        /// </summary>
        public static string GoodsName {
            get {
                return ResourceManager.GetString("GoodsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 谷歌分析ID 的本地化字符串。
        /// </summary>
        public static string GoogleAnalyticsID {
            get {
                return ResourceManager.GetString("GoogleAnalyticsID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高度 的本地化字符串。
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        public static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标 的本地化字符串。
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标类型 的本地化字符串。
        /// </summary>
        public static string IconType {
            get {
                return ResourceManager.GetString("IconType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片 的本地化字符串。
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片高度 的本地化字符串。
        /// </summary>
        public static string ImageHeight {
            get {
                return ResourceManager.GetString("ImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片 的本地化字符串。
        /// </summary>
        public static string ImageURL {
            get {
                return ResourceManager.GetString("ImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机轮播图 的本地化字符串。
        /// </summary>
        public static string ImageUrlMobile {
            get {
                return ResourceManager.GetString("ImageUrlMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PC轮播图 的本地化字符串。
        /// </summary>
        public static string ImageUrlPC {
            get {
                return ResourceManager.GetString("ImageUrlPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片宽度 的本地化字符串。
        /// </summary>
        public static string ImageWidth {
            get {
                return ResourceManager.GetString("ImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 的本地化字符串。
        /// </summary>
        public static string Importance {
            get {
                return ResourceManager.GetString("Importance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导航显示 的本地化字符串。
        /// </summary>
        public static string InMenu {
            get {
                return ResourceManager.GetString("InMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否关闭 的本地化字符串。
        /// </summary>
        public static string IsClose {
            get {
                return ResourceManager.GetString("IsClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        public static string IsDefault {
            get {
                return ResourceManager.GetString("IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关键字 的本地化字符串。
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后登录时间 的本地化字符串。
        /// </summary>
        public static string LastLogin {
            get {
                return ResourceManager.GetString("LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接 的本地化字符串。
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logo（登录页） 的本地化字符串。
        /// </summary>
        public static string LoginLogo {
            get {
                return ResourceManager.GetString("LoginLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logo 的本地化字符串。
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纵深 的本地化字符串。
        /// </summary>
        public static string Long {
            get {
                return ResourceManager.GetString("Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人 的本地化字符串。
        /// </summary>
        public static string MailTo {
            get {
                return ResourceManager.GetString("MailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主营业务 的本地化字符串。
        /// </summary>
        public static string MainBusiness {
            get {
                return ResourceManager.GetString("MainBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任职时间 的本地化字符串。
        /// </summary>
        public static string MasterTime {
            get {
                return ResourceManager.GetString("MasterTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单名称 的本地化字符串。
        /// </summary>
        public static string MenuName {
            get {
                return ResourceManager.GetString("MenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机 的本地化字符串。
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机验证码 的本地化字符串。
        /// </summary>
        public static string MobileCode {
            get {
                return ResourceManager.GetString("MobileCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月 的本地化字符串。
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频(MP4) 的本地化字符串。
        /// </summary>
        public static string Mp4Url {
            get {
                return ResourceManager.GetString("Mp4Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码 的本地化字符串。
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频(OGV) 的本地化字符串。
        /// </summary>
        public static string OgvUrl {
            get {
                return ResourceManager.GetString("OgvUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前密码 的本地化字符串。
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 团队组织 的本地化字符串。
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原价 的本地化字符串。
        /// </summary>
        public static string OriginalPrice {
            get {
                return ResourceManager.GetString("OriginalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 整体颜色 的本地化字符串。
        /// </summary>
        public static string OverallColor {
            get {
                return ResourceManager.GetString("OverallColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分页数 的本地化字符串。
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父级分类 的本地化字符串。
        /// </summary>
        public static string ParentCategory {
            get {
                return ResourceManager.GetString("ParentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话 的本地化字符串。
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 照片 的本地化字符串。
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品图片 的本地化字符串。
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 照片 的本地化字符串。
        /// </summary>
        public static string PhotoUrl {
            get {
                return ResourceManager.GetString("PhotoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口 的本地化字符串。
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 广告位 的本地化字符串。
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职位 的本地化字符串。
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览图 的本地化字符串。
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 价格 的本地化字符串。
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 负责人 的本地化字符串。
        /// </summary>
        public static string Principal {
            get {
                return ResourceManager.GetString("Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品分类 的本地化字符串。
        /// </summary>
        public static string ProductCategory {
            get {
                return ResourceManager.GetString("ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 品名 的本地化字符串。
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品编号 的本地化字符串。
        /// </summary>
        public static string ProductNo {
            get {
                return ResourceManager.GetString("ProductNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 省 的本地化字符串。
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布日期 的本地化字符串。
        /// </summary>
        public static string Pubdate {
            get {
                return ResourceManager.GetString("Pubdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二维码 的本地化字符串。
        /// </summary>
        public static string QRCode {
            get {
                return ResourceManager.GetString("QRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 问题 的本地化字符串。
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        public static string RealName {
            get {
                return ResourceManager.GetString("RealName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推荐 的本地化字符串。
        /// </summary>
        public static string Recommend {
            get {
                return ResourceManager.GetString("Recommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提名人 的本地化字符串。
        /// </summary>
        public static string Referrer {
            get {
                return ResourceManager.GetString("Referrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住我？ 的本地化字符串。
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必填 的本地化字符串。
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分辩率 的本地化字符串。
        /// </summary>
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色名称 的本地化字符串。
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 示意图 的本地化字符串。
        /// </summary>
        public static string Schematic {
            get {
                return ResourceManager.GetString("Schematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 别名 的本地化字符串。
        /// </summary>
        public static string SeoName {
            get {
                return ResourceManager.GetString("SeoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系列 的本地化字符串。
        /// </summary>
        public static string Serie {
            get {
                return ResourceManager.GetString("Serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网点名称 的本地化字符串。
        /// </summary>
        public static string ShopName {
            get {
                return ResourceManager.GetString("ShopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 域名 的本地化字符串。
        /// </summary>
        public static string SiteDomainName {
            get {
                return ResourceManager.GetString("SiteDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 站点名称 的本地化字符串。
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尺寸说明 的本地化字符串。
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 示意图 的本地化字符串。
        /// </summary>
        public static string Sketch {
            get {
                return ResourceManager.GetString("Sketch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料编码 的本地化字符串。
        /// </summary>
        public static string SkuCode {
            get {
                return ResourceManager.GetString("SkuCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SMTP服务器 的本地化字符串。
        /// </summary>
        public static string SmtpServer {
            get {
                return ResourceManager.GetString("SmtpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解决方案 的本地化字符串。
        /// </summary>
        public static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用与方案 的本地化字符串。
        /// </summary>
        public static string Solutions {
            get {
                return ResourceManager.GetString("Solutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 来源 的本地化字符串。
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规格 的本地化字符串。
        /// </summary>
        public static string Specification {
            get {
                return ResourceManager.GetString("Specification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SSL 的本地化字符串。
        /// </summary>
        public static string SSL {
            get {
                return ResourceManager.GetString("SSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库存 的本地化字符串。
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 店铺/基地 的本地化字符串。
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 门店名称 的本地化字符串。
        /// </summary>
        public static string StoreName {
            get {
                return ResourceManager.GetString("StoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 副标题 的本地化字符串。
        /// </summary>
        public static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 摘要 的本地化字符串。
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 面颜色 的本地化字符串。
        /// </summary>
        public static string SurfaceColor {
            get {
                return ResourceManager.GetString("SurfaceColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板名称 的本地化字符串。
        /// </summary>
        public static string TemplateName {
            get {
                return ResourceManager.GetString("TemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板编号 的本地化字符串。
        /// </summary>
        public static string TemplateNo {
            get {
                return ResourceManager.GetString("TemplateNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试邮箱 的本地化字符串。
        /// </summary>
        public static string TestEmail {
            get {
                return ResourceManager.GetString("TestEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩略图高度 的本地化字符串。
        /// </summary>
        public static string ThumbHeight {
            get {
                return ResourceManager.GetString("ThumbHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩略图 的本地化字符串。
        /// </summary>
        public static string Thumbnail {
            get {
                return ResourceManager.GetString("Thumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩略图宽度 的本地化字符串。
        /// </summary>
        public static string ThumbWidth {
            get {
                return ResourceManager.GetString("ThumbWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 距离左边 的本地化字符串。
        /// </summary>
        public static string ToLeft {
            get {
                return ResourceManager.GetString("ToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 距离顶部 的本地化字符串。
        /// </summary>
        public static string ToTop {
            get {
                return ResourceManager.GetString("ToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单位 的本地化字符串。
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网址 的本地化字符串。
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值 的本地化字符串。
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频 的本地化字符串。
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频地址 的本地化字符串。
        /// </summary>
        public static string VideoUrl {
            get {
                return ResourceManager.GetString("VideoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示次数 的本地化字符串。
        /// </summary>
        public static string ViewCount {
            get {
                return ResourceManager.GetString("ViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接 的本地化字符串。
        /// </summary>
        public static string WebLink {
            get {
                return ResourceManager.GetString("WebLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频(WEBM) 的本地化字符串。
        /// </summary>
        public static string WebmUrl {
            get {
                return ResourceManager.GetString("WebmUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工信部备案号 的本地化字符串。
        /// </summary>
        public static string WebNumber {
            get {
                return ResourceManager.GetString("WebNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微信 的本地化字符串。
        /// </summary>
        public static string Wechat {
            get {
                return ResourceManager.GetString("Wechat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微信号 的本地化字符串。
        /// </summary>
        public static string WechatId {
            get {
                return ResourceManager.GetString("WechatId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽度 的本地化字符串。
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 案例数量 的本地化字符串。
        /// </summary>
        public static string WorkCount {
            get {
                return ResourceManager.GetString("WorkCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作场所 的本地化字符串。
        /// </summary>
        public static string Workplace {
            get {
                return ResourceManager.GetString("Workplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年 的本地化字符串。
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
