//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.Resources.Admin {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Logs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logs() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIG.Resources.Admin.Logs", typeof(Logs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {0}批量彻底删除 的本地化字符串。
        /// </summary>
        public static string BulkRemove {
            get {
                return ResourceManager.GetString("BulkRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}批量移到回收站 的本地化字符串。
        /// </summary>
        public static string BulkTrash {
            get {
                return ResourceManager.GetString("BulkTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空{0}记录 的本地化字符串。
        /// </summary>
        public static string ClearAllMessage {
            get {
                return ResourceManager.GetString("ClearAllMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}:{1}被创建 的本地化字符串。
        /// </summary>
        public static string CreateMessage {
            get {
                return ResourceManager.GetString("CreateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}:{1}被删除 的本地化字符串。
        /// </summary>
        public static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建{0} 的本地化字符串。
        /// </summary>
        public static string ErrorCreateMessage {
            get {
                return ResourceManager.GetString("ErrorCreateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除{0} 的本地化字符串。
        /// </summary>
        public static string ErrorDeleteMessage {
            get {
                return ResourceManager.GetString("ErrorDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重设密码失败 的本地化字符串。
        /// </summary>
        public static string ErrorRestPwdMessage {
            get {
                return ResourceManager.GetString("ErrorRestPwdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改{0} 的本地化字符串。
        /// </summary>
        public static string ErrorUpdateMessage {
            get {
                return ResourceManager.GetString("ErrorUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 【{0}】回复邮件【{1}】 的本地化字符串。
        /// </summary>
        public static string ReplyEmail {
            get {
                return ResourceManager.GetString("ReplyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户[{0}]密码被重设 的本地化字符串。
        /// </summary>
        public static string RestPwdMessage {
            get {
                return ResourceManager.GetString("RestPwdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 【{0}】设置【{1}】为默认帐号 的本地化字符串。
        /// </summary>
        public static string SetDefaultEmailAccount {
            get {
                return ResourceManager.GetString("SetDefaultEmailAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 【{0}】设置【{1}】为默认收货地址 的本地化字符串。
        /// </summary>
        public static string SetDefaultRecipientInfo {
            get {
                return ResourceManager.GetString("SetDefaultRecipientInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}:{1}被修改 的本地化字符串。
        /// </summary>
        public static string UpdateMessage {
            get {
                return ResourceManager.GetString("UpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户[{0}]登录 的本地化字符串。
        /// </summary>
        public static string UserLoginMessage {
            get {
                return ResourceManager.GetString("UserLoginMessage", resourceCulture);
            }
        }
    }
}
