//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.Resources.Admin {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIG.Resources.Admin.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败 的本地化字符串。
        /// </summary>
        public static string AlertActionFailure {
            get {
                return ResourceManager.GetString("AlertActionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功 的本地化字符串。
        /// </summary>
        public static string AlertActionSuccess {
            get {
                return ResourceManager.GetString("AlertActionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已成功加入收藏夹 的本地化字符串。
        /// </summary>
        public static string AlertAddCollectionSuccess {
            get {
                return ResourceManager.GetString("AlertAddCollectionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建{0}失败 的本地化字符串。
        /// </summary>
        public static string AlertCreateFailure {
            get {
                return ResourceManager.GetString("AlertCreateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建{0}成功 的本地化字符串。
        /// </summary>
        public static string AlertCreateSuccess {
            get {
                return ResourceManager.GetString("AlertCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除{0}失败 的本地化字符串。
        /// </summary>
        public static string AlertDeleteFailure {
            get {
                return ResourceManager.GetString("AlertDeleteFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除{0}失败，还存在子项目！ 的本地化字符串。
        /// </summary>
        public static string AlertDeleteFailureHasChild {
            get {
                return ResourceManager.GetString("AlertDeleteFailureHasChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除{0}成功 的本地化字符串。
        /// </summary>
        public static string AlertDeleteSuccess {
            get {
                return ResourceManager.GetString("AlertDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}还原失败 的本地化字符串。
        /// </summary>
        public static string AlertRestoreFailure {
            get {
                return ResourceManager.GetString("AlertRestoreFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}还原成功 的本地化字符串。
        /// </summary>
        public static string AlertRestoreSuccess {
            get {
                return ResourceManager.GetString("AlertRestoreSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}发送失败 的本地化字符串。
        /// </summary>
        public static string AlertSendFailure {
            get {
                return ResourceManager.GetString("AlertSendFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}发送成功 的本地化字符串。
        /// </summary>
        public static string AlertSendSuccess {
            get {
                return ResourceManager.GetString("AlertSendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改{0}失败 的本地化字符串。
        /// </summary>
        public static string AlertUpdateFailure {
            get {
                return ResourceManager.GetString("AlertUpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改{0}成功 的本地化字符串。
        /// </summary>
        public static string AlertUpdateSuccess {
            get {
                return ResourceManager.GetString("AlertUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot add null entity into {0} repository 的本地化字符串。
        /// </summary>
        public static string CannotAddNullEntity {
            get {
                return ResourceManager.GetString("CannotAddNullEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot modify null item into {0} repository 的本地化字符串。
        /// </summary>
        public static string CannotModifyNullEntity {
            get {
                return ResourceManager.GetString("CannotModifyNullEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱已被注册 的本地化字符串。
        /// </summary>
        public static string CannotRegisterEmail {
            get {
                return ResourceManager.GetString("CannotRegisterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名已被注册 的本地化字符串。
        /// </summary>
        public static string CannotRegisterUserName {
            get {
                return ResourceManager.GetString("CannotRegisterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot remove null entity into {0} repository 的本地化字符串。
        /// </summary>
        public static string CannotRemoveNullEntity {
            get {
                return ResourceManager.GetString("CannotRemoveNullEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot track null item into {0} repository 的本地化字符串。
        /// </summary>
        public static string CannotTrackNullEntity {
            get {
                return ResourceManager.GetString("CannotTrackNullEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入有效的{0} 的本地化字符串。
        /// </summary>
        public static string CheckFormat {
            get {
                return ResourceManager.GetString("CheckFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter expression cannot be null 的本地化字符串。
        /// </summary>
        public static string FilterCannotBeNullException {
            get {
                return ResourceManager.GetString("FilterCannotBeNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此{0}下面还有{1}存在，不能删除！ 的本地化字符串。
        /// </summary>
        public static string HasChildCanNotDelete {
            get {
                return ResourceManager.GetString("HasChildCanNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到可编辑的项 的本地化字符串。
        /// </summary>
        public static string HttpNotFound {
            get {
                return ResourceManager.GetString("HttpNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Includes expression cannot be null 的本地化字符串。
        /// </summary>
        public static string IncludesCannotBeNullException {
            get {
                return ResourceManager.GetString("IncludesCannotBeNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PageCount must be positive value 的本地化字符串。
        /// </summary>
        public static string InvalidPageCountException {
            get {
                return ResourceManager.GetString("InvalidPageCountException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PageIndex must be positive value 的本地化字符串。
        /// </summary>
        public static string InvalidPageIndexException {
            get {
                return ResourceManager.GetString("InvalidPageIndexException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人邮箱地址缺失，请提示网站管理员！ 的本地化字符串。
        /// </summary>
        public static string NoMailTo {
            get {
                return ResourceManager.GetString("NoMailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须是创始人才可以删除此{0}！ 的本地化字符串。
        /// </summary>
        public static string NotFounderCanNotDelete {
            get {
                return ResourceManager.GetString("NotFounderCanNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前用户不存在 的本地化字符串。
        /// </summary>
        public static string NoUser {
            get {
                return ResourceManager.GetString("NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrderBy expression cannot be null 的本地化字符串。
        /// </summary>
        public static string OrderByExpressionCannotBeNullException {
            get {
                return ResourceManager.GetString("OrderByExpressionCannotBeNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前用户密码错误 的本地化字符串。
        /// </summary>
        public static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此产品已收藏 的本地化字符串。
        /// </summary>
        public static string ProductIsCollectioned {
            get {
                return ResourceManager.GetString("ProductIsCollectioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先设置默认发送帐号 的本地化字符串。
        /// </summary>
        public static string SetDefaultEmailAccount {
            get {
                return ResourceManager.GetString("SetDefaultEmailAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specification cannot be null 的本地化字符串。
        /// </summary>
        public static string SpecificationIsNullException {
            get {
                return ResourceManager.GetString("SpecificationIsNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前帐号未登录 的本地化字符串。
        /// </summary>
        public static string UnLogin {
            get {
                return ResourceManager.GetString("UnLogin", resourceCulture);
            }
        }
    }
}
