//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.Resources.Admin {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validations() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIG.Resources.Admin.Validations", typeof(Validations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 密码和确认密码不匹配 的本地化字符串。
        /// </summary>
        public static string ComparePassword {
            get {
                return ResourceManager.GetString("ComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失效的价格，最大输入18位数 的本地化字符串。
        /// </summary>
        public static string DecimalFormat {
            get {
                return ResourceManager.GetString("DecimalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的邮箱地址格式无效 的本地化字符串。
        /// </summary>
        public static string EmailAddressInvalidFormat {
            get {
                return ResourceManager.GetString("EmailAddressInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的{0}格式无效 的本地化字符串。
        /// </summary>
        public static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的格式无效，只限英文字母和数字 的本地化字符串。
        /// </summary>
        public static string InvalidFormatEnglishAndNumber {
            get {
                return ResourceManager.GetString("InvalidFormatEnglishAndNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的格式无效，只限英文字母，下划线 的本地化字符串。
        /// </summary>
        public static string InvalidFormatEnglishAndUnderline {
            get {
                return ResourceManager.GetString("InvalidFormatEnglishAndUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的格式无效，只限英文字母 的本地化字符串。
        /// </summary>
        public static string InvalidFormatOnlyEnglish {
            get {
                return ResourceManager.GetString("InvalidFormatOnlyEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的格式无效，只限英文字母、数字、下划线和中杆号 的本地化字符串。
        /// </summary>
        public static string InvalidFormatSEOUrl {
            get {
                return ResourceManager.GetString("InvalidFormatSEOUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经存在此{0} 的本地化字符串。
        /// </summary>
        public static string IsExist {
            get {
                return ResourceManager.GetString("IsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}字符长度不可大于{1} 的本地化字符串。
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不允许输入空白 的本地化字符串。
        /// </summary>
        public static string RENotWhiteSpace {
            get {
                return ResourceManager.GetString("RENotWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入{0} 的本地化字符串。
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择{0} 的本地化字符串。
        /// </summary>
        public static string RequiredSelect {
            get {
                return ResourceManager.GetString("RequiredSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 必须至少包含 {2} 个字符 的本地化字符串。
        /// </summary>
        public static string StringLengthWithMiniLength {
            get {
                return ResourceManager.GetString("StringLengthWithMiniLength", resourceCulture);
            }
        }
    }
}
