//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIG.Resources.Front {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIG.Resources.Front.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功！ 的本地化字符串。
        /// </summary>
        public static string AlertActionSuccess {
            get {
                return ResourceManager.GetString("AlertActionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已成功加入收藏夹 的本地化字符串。
        /// </summary>
        public static string AlertAddCollectionSuccess {
            get {
                return ResourceManager.GetString("AlertAddCollectionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}创建成功！ 的本地化字符串。
        /// </summary>
        public static string AlertCreateSuccess {
            get {
                return ResourceManager.GetString("AlertCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}删除失败！ 的本地化字符串。
        /// </summary>
        public static string AlertDeleteFailure {
            get {
                return ResourceManager.GetString("AlertDeleteFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}已成功删除！ 的本地化字符串。
        /// </summary>
        public static string AlertDeleteSuccess {
            get {
                return ResourceManager.GetString("AlertDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}更新失败 的本地化字符串。
        /// </summary>
        public static string AlertUpdateFailure {
            get {
                return ResourceManager.GetString("AlertUpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}更新成功 的本地化字符串。
        /// </summary>
        public static string AlertUpdateSuccess {
            get {
                return ResourceManager.GetString("AlertUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱已经存在！ 的本地化字符串。
        /// </summary>
        public static string CannotRegisterEmail {
            get {
                return ResourceManager.GetString("CannotRegisterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名已经存在！ 的本地化字符串。
        /// </summary>
        public static string CannotRegisterUserName {
            get {
                return ResourceManager.GetString("CannotRegisterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除收藏 的本地化字符串。
        /// </summary>
        public static string DeleteCollection {
            get {
                return ResourceManager.GetString("DeleteCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮件已发送成功！ 的本地化字符串。
        /// </summary>
        public static string EmailSentSuccess {
            get {
                return ResourceManager.GetString("EmailSentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到任何数据 的本地化字符串。
        /// </summary>
        public static string HttpNotFound {
            get {
                return ResourceManager.GetString("HttpNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的用户名或密码！ 的本地化字符串。
        /// </summary>
        public static string InvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮件模板【{0}】不存在，请联系管理员！ 的本地化字符串。
        /// </summary>
        public static string NoEmailTemplate {
            get {
                return ResourceManager.GetString("NoEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不存在！ 的本地化字符串。
        /// </summary>
        public static string NoUser {
            get {
                return ResourceManager.GetString("NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原密码错误！ 的本地化字符串。
        /// </summary>
        public static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此产品已收藏 的本地化字符串。
        /// </summary>
        public static string ProductIsCollectioned {
            get {
                return ResourceManager.GetString("ProductIsCollectioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码重设邮件已经发送到您的注册邮箱，请及时查收，30分钟失效！ 的本地化字符串。
        /// </summary>
        public static string ResetPasswordEmailSentSuccess {
            get {
                return ResourceManager.GetString("ResetPasswordEmailSentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先登录网站！ 的本地化字符串。
        /// </summary>
        public static string UnLogin {
            get {
                return ResourceManager.GetString("UnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎光临！ 的本地化字符串。
        /// </summary>
        public static string Wellcome {
            get {
                return ResourceManager.GetString("Wellcome", resourceCulture);
            }
        }
    }
}
